version: '3.7'
services:
  client-dev:
    image: doughterd/template-client:dev
    command: ["npm", "run", "start"]
    build: 
      context: ./client
      target: dev
    ports:
      - 3000:3000
    links:
      - server-dev
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
  server-dev:
    image: doughtnerd/template-server:dev
    build:
      context: ./server
      target: dev
    ports:
      - 3005:3005
      - 9229:9229
    volumes: 
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    
